spring:
  application:
    name: hello-spring-cloud-zipkin
  spring:
    boot:
      admin:
        client:
          url: http://localhost:8084

# zipkin默认端口
server:
  port: 9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false