spring:
  application:
    name: hello-spring-cloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://gitlab.com/kdnight/spring-cloud-config.git
          search-paths: respo
          username: 870507307@qq.com
          password: zxcvbnm120
  zipkin:
    base-url: http://localhost:9411
  spring:
    boot:
      admin:
        client:
          url: http://localhost:8084
# 不可改，否则用bootstrap。properties里改
server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/